# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI with Parallelism

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.nvm.outputs.NVMRC }}
    steps:
    - uses: actions/checkout@v2

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v2
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

  npm-ci:
    name: Install Dependencies
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "${{ needs.setup.outputs.node-version }}"
    - run: npm ci

  npm-test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: npm-ci
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "${{ needs.setup.outputs.node-version }}"
    - run: npm test

  nestjs-test:
    name: Test NestJS
    runs-on: ubuntu-latest
    needs: npm-ci
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "${{ needs.setup.outputs.node-version }}"
    - run: npm run test:nestjs

  mocha-test:
    name: Test Mocha
    runs-on: ubuntu-latest
    needs: npm-ci
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "${{ needs.setup.outputs.node-version }}"
    - run: npm run test:mocha

